#############################################################
# Dockerfile tools for single-cell methylation pipeline
#############################################################

FROM quay.io/neksa/pipelines

# ENV VAR VALUE
ENV PATH /home/ubuntu/Epigenomics_CWL/bin:/home/ubuntu/bin:/home/ubuntu/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV HOME /home/ubuntu
WORKDIR /home/ubuntu

USER ubuntu

CMD bash
