
FROM quay.io/ncbi_hackathons/epigenomics_base

# ENV VAR VALUE
ENV PATH /home/ubuntu/Epigenomics_CWL/bin:/home/ubuntu/bin:/home/ubuntu/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV HOME /home/ubuntu
WORKDIR /home/ubuntu

USER ubuntu

CMD bash
